name: UserInterface
version: ${project.version}
main: me.xemor.userinterface.UserInterface
api-version: 1.17
authors: [ Xemor_ ]
depend: [floodgate, ProtocolLib]
description: Allows you to add Bedrock-Java cross compatible GUIs
